language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pysmt-install --z3 --confirm-agreement
  - pysmt-install --check
script: pytest --flake8 --cov=magnum --cov-report=html
before_install:
  - sudo apt-get install python-glpk
  - sudo apt-get install glpk-utils
  - sudo apt-get install z3
  
after_success:
  - codecov
